name: create_release_from_tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        id: image
        with:
          file: ../../Dockerfile
          platforms: linux/amd64
          build-args: AGENT_VERSION=7.43.0-1
          tags: datadog-aas
          load: true
      - name: Extract zip file
        run: docker cp $(docker create datadog-aas):/datadog-aas.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ github.ref_name }}
          files: datadog-aas.zip