name: create_release_from_tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        # - name: Build binaries
        #   id: docker-build
        #   run: docker buildx build --platform=linux/amd64 -f ../../Dockerfile --build-arg AGENT_VERSION=7.43.0-1 .
        # - name: Release
        #   uses: softprops/action-gh-release@v1
        #   with:
        #     files:
